### PR TITLE
DTLSConnector class instantiation fixed for console client.

### PR DESCRIPTION
**Pull request by fimperato**
DTLSConnector class instantiation fixed for console client.

### CODE REVIEW

**Comment by sophokles73** [comment]
Hi @fimperato,

many thanks for fixing this :-) In order for me to merge your PR, we need you to sign an (Eclipse Contributor License Agreement (CLA))[https://www.eclipse.org/legal/CLA.php]. If this is too much of a hassle for you, I can also merge the changes on my own account. However, If you plan to provide additional PRs for any eclipse project in the future (which I hope you do), it would definitely worth the effort to sign the CLA. In any case, I also need you to add a Signed-of-by foot to the commit message. Can you do that?

**Comment by fimperato** [comment]
I've just signed the Eclipse Contributor License Agreement (to end of sign the page show the message: The CLA we have on record for you will expire on 2018-07-22 [...])
And what type of commit message can I write to "a Signed-off-by foot to the commit message"?

**Comment by fimperato** [comment]
Hi @sophokles73  
I've finally found option to add a signed off by, so i've added a commit message using that option (with result: "Signed-off-by: Francesco Imperato <francesco.imperato.ita@gmail.com>").

**Comment by sophokles73** [comment]
I am sorry, but now the lines you changed start with an inital tab but then go on with spaces for indenting to the right level :-(
Your PR also contains two commits instead of one. I think it would be easiest for you if you'd start from scratch with a new branch from californium.tool's current master, re-apply the few changes and create a commit including your Signed-off-by footer and create a new PR from it. I think this will be much quicker than trying to resolve all outstanding issues based on your current branch ...

**Comment by fimperato** [comment]
I've followed your advice: there is a new pull request now (#5).

**Comment by sophokles73** [comment]
Replaced by #5

**Pull request closed without merging**
