### PR TITLE
Fix Observe support for CoAP command-line client

### PR DESCRIPTION
**Pull request by jasta**
When using the cf-client tool, specifying `--extended-method OBSERVE`
would always result in a stall after the first response due to a missing
NotificationListener that is normally established through the canonical
use of CoapClient.observe(...).  The command-line client, however,
manually interacts with request and request.send() which lacked this
glue.  This change simply adds that glue manually back in rather than
switching to the canonical approach.

Tested against libcoap's coap-server as with:

    $ coap-server -v 9 &
    $ java -jar run/cf-client-3.6.0-SNAPSHOT.jar --extended-method OBSERVE coap://localhost/time

### CODE REVIEW

**Comment by jasta** [comment]
I believe I have signed the ECA, not sure why it is still saying that I have not.  Perhaps it just takes a while to update.

**Comment by boaks** [comment]
Good catch an nice fix!
Thanks a lot!

**Comment by boaks** [comment]
LGTM

**Comment by boaks** [comment]
Would it be possible, that you squash your commits into one?
squash and force push on your branch?

**Comment by jasta** [comment]
Sure no problem, I'll squash them today

**Pull request merged**
