### PR TITLE
Display malformed payload

### PR DESCRIPTION
**Pull request by boaks**
Addresses concerns of PR #63

### CODE REVIEW

**Review by sophokles73 — COMMENTED** [review]
where does the cbor PNG come from?

**Comment by boaks** [comment]
That's a copy of the blank.png and I added the text.

**Comment by boaks** [comment]
I guess, my git copy back and forward added it by mistake. I remove the png from the commit.

**Comment by boaks** [comment]
It was just because this PR was based on the other PR #63. 
I cleaned it up.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
