### PR TITLE
File path must use platform specific separator

### PR DESCRIPTION
**Pull request by starksm64**
Signed-off-by: Scott Stark <starksm64@gmail.com>
This addressed issue #11

### CODE REVIEW

**Comment by mkovatsc** [comment]
Hi Scott

Thanks for raising this! It was a really bad choice to go with a Windows path, especially since Java handles slashes correctly on all platforms (i.e., normal slashes work on Windows!). I think we could simplify this to defining filePath = "src/main/resources/data/image/" and skip the replace().

As far as I understood it, separatorChar should only come when displaying paths to the user.

Fine with that? Would you do this in your branch? I will merge it then, since we now had all this signing off trouble :)

Thanks
Matthias

**Comment by sophokles73** [comment]
+1 for using forward slashes in the path in the first place ...

**Comment by sophokles73** [comment]
@starksm64, are you going to update your PR according to Matthias' suggestion? We can then merge it and close the corresponding issue ...

**Comment by starksm64** [comment]
Ok, I have changed the commit to just use forward slashes.

**Comment by sophokles73** [comment]
Merged in 8c0ec4bd34cc8b5b59c170739484f5547a6ee1fa

**Pull request closed without merging**
